<?php
    /**
     *
     * NOTICE OF LICENSE
     *
     * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
     *
     * @company   	ThirdLevel
     * @package    	MercadoLivre
     * @author      André Fuhrman (andrefuhrman@gmail.com)
     * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
     *
     */
?>

<div class="entry-view">

    <fieldset id="grop_fields">
        <p><b><?php echo Mage::helper('mercadolivre')->__('MercadoLivre Extension for Magento') ?></b></p>
        <p><?php echo Mage::helper('mercadolivre')->__('Version: ') . Mage::helper('mercadolivre')->getExtensionVersion(); ?></p></br>
        <p><?php echo Mage::helper('mercadolivre')->RetrieveCopyrightInformation(); ?></p>
    </fieldset>

</div>