<?php
/**
 * @var Ophirah_Qquoteadv_Block_Renderers_Grouped $this
 */
?>
<?php foreach ($this->getQuote()->getItemsCollection() as $quoteItem): ?>
    <div class="grouped-product-container grouped-product">
        <div class="product-image">
            <div class="product-image-container product-image-grouped">
                <img src="<?php echo $this->getProductImage(180, $quoteItem->getProduct()) ?>" alt="close"/>
            </div>
        </div>
        <div class="product-details">
            <div class="configurable-options">
                <ul>
                    <li><h2><?php echo $quoteItem->getName() ?></h2></li>
                    <li>
                        <span class="option-item"><?php echo $this->__('Price') ?>:
                            <?php echo $this->getProductPrice($quoteItem->getProduct()); ?>
                        </span>
                    </li>
                    <li class="option-header-border">
                        <span class="option-item">
                            <?php echo $this->__('Qty')?>: <?php echo $quoteItem->getQty() ?>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php if($this->getError()): ?>
    <div id="add-to-quote-errors" style="display: none;">
        <?php echo $this->getError(); ?>
    </div>
<?php endif; ?>
