<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* https://moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        history.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2016 Moogento <info@moogento.com> / All rights reserved.
* @license    https://moogento.com/License.html
*/ 
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders'); ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_orders->getSize()): ?>
    <table class="data-table" id="my-orders-table">
        <col width="1"/>
        <col width="1"/>
        <col/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <thead>
        <tr>
            <th class="number"><?php echo $this->__('Order #') ?></th>
            <th class="date"><?php echo $this->__('Date') ?></th>
            <th class="ship"><?php echo $this->__('Ship To') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th class="status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
            <tr>
                <td class="number"><?php echo $_order->getRealOrderId() ?></td>
                <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                <td class="ship"><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                <td class="a-center">
					<span class="nobr">
					<a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
						<?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
						<?php if ($this->helper('sales/reorder')->canReorder($_order)) { ?>
							<span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>"
																class="link-reorder"><?php echo $this->__('Reorder') ?></a>
						<?php }
						
						if ((Mage::getStoreConfig('pickpack_options/button_invoice/frontend_order_pdf_invoice_button') == 1) && (Mage::getStoreConfig('pickpack_options/button_invoice/frontend_order_pdf_packing_sheet_button') == 1)) { ?>
							<br/>
							<a href="<?php echo $this->getUrl('pickpack/order/mooorderinvoice/order_id/' . $_order->getId()) ?>" class="link-pdf-invoice "><?php echo $this->__('PDF Invoice') ?></a>
							<span class="separator pdf-packing-sheet">|</span> 
							<a href="<?php echo $this->getUrl('pickpack/order/mooordershipment/order_id/' . $_order->getId()) ?>" class="link-pdf-packing-ship"><?php echo $this->__('PDF Packing Sheet') ?></a>
						<?php 
						} 
						else 
						{ 
							if (Mage::getStoreConfig('pickpack_options/button_invoice/frontend_order_pdf_invoice_button')) 
							{ ?>
								<span class="separator pdf-invoice">|</span> 
								<a href="<?php echo $this->getUrl('pickpack/order/mooorderinvoice/order_id/' . $_order->getId()) ?>" class="link-pdf-invoice "><?php echo $this->__('PDF Invoice') ?></a>
							<?php 
							}
							
							if (Mage::getStoreConfig('pickpack_options/button_invoice/frontend_order_pdf_packing_sheet_button'))
							{ ?>
									<span class="separator pdf-packing-sheet">|</span> <a href="<?php echo $this->getUrl('pickpack/order/mooordershipment/order_id/' . $_order->getId()) ?>" class="link-pdf-packing-ship"><?php echo $this->__('PDF Packing Sheet') ?></a>
								<?php 
							}
						} ?>
					</span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>