<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title><?php echo $this->pageTitle?></title>
<base href="<?php echo $this->getSkinUrl()?>" />
</head>
<body>
    <div class="wrapper">
        <div class="page">
            <div class="main-container">
                <div class="main col1-layout">
			<?php require_once $contentTemplate; ?>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
