<?php
?>
<!DOCTYPE html>

<!-- 
  Theme: Lost in the Clouds - Error 404 v1.2
  Author: adraft [http://themeforest.net/user/adraft?ref=adraft]
  Date: 05-07-2011
  Last update: 15-08-2013
-->

<head>
	<meta charset="utf-8">
	<title>Lost in the Clouds - Error 404</title>
	<meta name="description" content="Simple and aesthetic template with animated background">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<link rel="stylesheet" type="text/css" href="css/reset.css" />	
	<link rel="stylesheet" type="text/css" href="css/main.css" />
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Inconsolata&amp;v1" />
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Candal&amp;v1" />
	<link rel="shortcut icon" href="favicon.ico" />
	
	<!--[if lte IE 8]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body>
	<div id="container">
		<div id="stage" class="stage">
			<div id="clouds" class="stage"></div>
		</div>
		
		<div id="ticket">
			<section id="ticket_left">
				<p class="text1_a">vuelo perdido</p>
				<p class="text2_a">no encontrado</p>
				<p class="text3_a">Error 404</p>
				<p class="text4_a">Sorry!</p>
				<p class="text5_a">Desde</p>
				<p class="text6_a">Algun lugar</p>
				<p class="text7_a">A</p>
				<p class="text8_a">ninguna parte</p>			
				<p class="text9_a">Asiento</p>
				<p class="text10_a">404</p>
				<p class="text11_a">Por favor intente otro vuelo</p>
				<nav class="text12_a">
					<ul>
						<li><a href="http://www.peta.cl">catalogo</a></li>
						<li><a href="http://www.peta.cl/la-empresa">nosotros</a></li>
						<li><a href="http://www.peta.cl/servicios">despachos</a></li>
						<li><a href="http://www.peta.cl/garantias">garantias</a></li>
						<li><a href="http://www.peta.cl/contacts">contacto</a></li>
				  </ul>
			  </nav>			
			</section>
			
			<section id="ticket_right">
				<p class="text1_b">primera clase</p>
				<p class="text2_b">perdido en las nubes</p>
				<p class="text3_b">Desde</p>
				<p class="text4_b">algun lugar</p>
				<p class="text5_b">A</p>
				<p class="text6_b">ninguna parte</p>
				<p class="text7_b">Asiento</p>
				<p class="text8_b">404</p>
				<p class="text9_b">1</p>
				<p class="text10_b">103076498</p>
			</section>
		</div>
	</div>

	<script src="js/jquery-1.8.3.min.js" type="text/javascript"></script>
	<script src="js/jquery.spritely-0.5.js" type="text/javascript"></script>

	<script type="text/javascript">
		(function($) {
			$(document).ready(function() {
				$('#clouds').pan({fps: 40, speed: 0.7, dir: 'right', depth: 10});
			});
		})(jQuery);	
	</script>
</body>
</html>
