<script type="text/javascript">
    //<![CDATA[
    function resetPickpack() {
	
	var r = confirm("Are you sure you want to rest all pickPack config settings?");
        if (r == true) {
                  new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
                        method:     'get',
                        onSuccess: function(transport){
 
                         if (transport.responseText){
                             alert(transport.responseText);
                             window.location.href = window.location.href;
                        }
                 else
                    arlert('Can\'t reset pickPack at the moment.');
                 }
            });
       } else {      
   	    x = "Cancelled Reset";
      } 		  	
    }
    //]]>
</script>
 
<?php echo $this->getButtonHtml() ?>